# Generated by Django 3.1.3 on 2021-07-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialDetail',
            fields=[
                ('materialID', models.AutoField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(blank=True, max_length=100, null=True)),
                ('material_unit', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'material_detail',
            },
        ),
    ]
