# Generated by Django 3.1.3 on 2021-07-02 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('siteDetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance', models.CharField(max_length=50, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('latitude', models.CharField(max_length=50, null=True)),
                ('longitude', models.CharField(max_length=50, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteDetails.sitedetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_attendance',
            },
        ),
    ]
